### ISSUE TITLE
Synergies with mapme.biodiversity project?

### ISSUE THREAD

**Issue by cboettig** [GEO-BON/bon-in-a-box-pipelines#113]
BIAB looks like it may have strong synergies with the [MAPme Biodiversity](https://mapme-initiative.org/) project developed under support of the German Development Bank KfW, e.g. https://github.com/mapme-initiative/mapme.biodiversity

**Comment by jmlord** [comment]
We finally had a meeting with Darius today. Discussion was nice and we identified the complementary nature of the two products.

The mapme.biodiversity package mainly does zonal statistics on globally available layers. Some of it's modules could be wrapped in a step and serve as an input to BON in a Box pipelines. Unfortunately, no immediate synergy was identified and the future will tell depending on pipeline needs.

See the [list of resources and indicators](https://mapme-initiative.github.io/mapme.biodiversity/index.html#available-resources-and-indicators) for inspiration.
