### ISSUE TITLE
Use distance sampling for the backgrounds in BRT example

### ISSUE THREAD

**Issue by tpoisot** [GEO-BON/bon-in-a-box-pipelines#118]
When JuliaRegistries/General#93404 is merged, this will replace `sample` by `backgroundpoints`, and add a `DistanceToEvent` method for background points, which will allow using the same-ish background generation in the MaxEnt and BRT pipelines (@glaroc and I discussed this last week).

Just putting a pin in this so we can update the pipeline accordingly.

**Comment by frousseu** [comment]
Is this method uniformally sampling from a fixed width radius around each observations or from a function with decreasing probability the further you go from each observations? If the former, there is already the background thickening method from the createBackground function in the maxent pipeline.

**Comment by tpoisot** [comment]
Currently it generates a layer of distances, and then you can use this information however you want for sampling (but we also have a `WithinRadius` method to do uniform sampling within a distance)
