### ISSUE TITLE
Increase speed of R-scripts

### ISSUE THREAD

**Issue by Oselmoni** [GEO-BON/bon-in-a-box-pipelines#175]
**Describe the bug**
I created a simple example of an R-script that runs much slower in bon-in-a-box than in R studio. 

**Steps To Reproduce**
Run the script called "speedTest.R" from the GFS_indicatorstool folder, on the genes-from-space branch, 

**Expected behavior**
The script takes less than a second in Rstudio on a macbook M1. On my docker instance the script takes 36 seconds.

**Comment by Oselmoni** [comment]
Checking "Use Rosetta for x86_64/amd64 emulation on Apple Silicon" in dockers preferences solved the issue.

**Comment by jmlord** [comment]
Documented: https://github.com/GEO-BON/bon-in-a-box-pipeline-engine/commit/70e14de1b9bd45a5811f98d55d29bc80b3aa8373
